max_anime_frames=5
[[Graphics]]
name="Example One"
mode="grit"
options=[
    "-fts",				    # Create s file
    "-m!",				    # No Map
    "-gB8",				    # output 8bpp graphics
    "-gu8",                 # output as bytes
    "-gT FF00FF",		    # RGB 24 BIT
    "-pS",				    # Share pallet
    "-Mh2",			        # output data as byte array
    "-Mw2",         	
    "-OSharedExampleOne"       # Shared pallet name
]
files=[
    "gfx/RedSqaure.aseprite",
    "gfx/YellowSqaure.psd"
]
[[Graphics.animes]]
for="GfxRedSqaure.h"
size="32x32"
frames=["idle", "crying"]

[[Graphics]]
name="Example Two"
mode="grit"
options=[
    "-fts",				    # Create s file
    "-m!",				    # No Map
    "-gB8",				    # output 8bpp graphics
    "-gu8",                 # output as bytes
    "-gT FF00FF",		    # RGB 24 BIT
    "-pS",				    # Share pallet
    "-Mh2",			        # output data as byte array
    "-Mw2",         	
    "-OSharedExampleTwo"       # Shared pallet name
]
files=[
    "gfx/BlueSqaure.png",
]

[[Graphics]]
name="example_three"
mode="bmp2gba"
options=[
    "--transparent-color", "FF00FF",
    "--brute-force-count", "250000"
]
files=[
    "gfx/backgrounds/crBiscut.png",
    "gfx/backgrounds/crBuildings.aseprite",
    "gfx/backgrounds/mgBeach.psd",
]
